language:
   - cpp

before_script:
    - cd test
    - mkdir lib && cd lib
    - git clone https://github.com/google/googletest.git && mv googletest gtest
    - cd ../..
    - mkdir ci_test
    - cd ci_test
    - cmake ..
    - make

script:
    - ./test/Rockarbon_Test