language:
  - cpp

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev wget unzip
  - cd test
  - mkdir lib && cd lib
  - git clone https://github.com/google/googletest.git && mv googletest gtest
  - mkdir cryptopp && cd cryptopp
  - wget https://cryptopp.com/cryptopp610.zip
  - unzip cryptopp610.zip
  - make
  - make install
  - cd ../../..
  - mkdir ci_test
  - cd ci_test
  - cmake ..
  - make

script:
  - ./test/Rockarbon_Test